ALTER TABLE "UploadedSchedule" ADD COLUMN IF NOT EXISTS "imageUrl" TEXT;
ALTER TABLE "UploadedSchedule" ADD COLUMN IF NOT EXISTS "imagePosition" TEXT;
ALTER TABLE "UploadedSchedule" ADD COLUMN IF NOT EXISTS "imageScale" DOUBLE PRECISION;
